### ISSUE TITLE
Peggle Deluxe to HTML

### ISSUE THREAD

**Issue by sapphic-wallflower** [sapphic-wallflower/into-the-void#12]
# To-Do List

- [x] Find & input banner.
- [x] Summary content
- [x] First impressions content
- [x] Finding footing content
- [x] Diving in content
- [x] Final thoughts content
- [x] Completion record
- [x] Image gallery
