### ISSUE TITLE
Undertale to HTML

### ISSUE THREAD

**Issue by sapphic-wallflower** [sapphic-wallflower/into-the-void#15]
# To-Do List

- [ ] Find & input banner.
- [ ] Summary content
- [ ] First impressions content
- [ ] Finding footing content
- [ ] Diving in content
- [ ] Final thoughts content
- [ ] Completion record
- [ ] Image gallery
