### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by sapphic-wallflower** [sapphic-wallflower/into-the-void#48]
# To-Do List

## Site
- [x] Choose a site-wide font.
- [x] Choose a site-wide background.
- [x] Move the CSS to its own file.
- [x] Decide on a colour scheme.
- [x] Comments explaining what each CSS does.

## Nav
- [x] Spacing between each item in the list.
- [x] Replace bullet list with a cute image for each bullet. (Heart? Star? Emoticons?)
- [x] Scroll with the screen, always having access to the sidebar. 
- [x] Links (Bookmarks, essentially)

## Footer
- [x] "Let your love be the thing that defines you"
- [x] Music note ASCII that links to the senses fail song
